language: objective-c

osx_image: xcode8.3

install:
  - nvm install 7
  - rm -Rf "${TMPDIR}/jest_preprocess_cache"
  - brew install yarn --ignore-dependencies
  - brew install watchman
  - yarn install

xcode_project: RNReactArkit.xcodeproj # path to your xcodeproj folder
xcode_scheme: RNReactArkit

matrix:
  - fast_finish: true # Fail the whole build as soon as one test type fails. Should help with Travis capacity issues (very long queues).

# The order of these tests says which are more likely to run first and fail the whole build fast.
env:
  - TEST_TYPE=objc-ios
  - TEST_TYPE=podspecs

branches:
  only:
    - master
    - /^.*-stable$/
